### ISSUE TITLE
Dragonflight Milling does not appear to be implemented

### ISSUE THREAD

**Issue by grimmtooth** [nightazn/GupPet#2]
This probably also applies to prospecting, as well.

Image of Inscription interface (native)

![image](https://user-images.githubusercontent.com/16244433/204684721-2b85e95e-43d2-4ca3-8cf2-d9805d652d53.png)

So, you select Dragon Isles Milling, and you get a little panel with a little plus on it. Select that panel and you get a menu of available herbs (and unavailable if you so choose)

You then have the option to choose how many grinds of the mill or just select "mill all".

All this is currently missing in the current alpha release (alpha18).

Let me know if you need any files or logs or whatnot.

**Comment by nightazn** [comment]
I think you clicked on the wrong mod.. unless this is an enhancement request for GupPet :D

**Comment by grimmtooth** [comment]
Oops, wrong tab! Sorry, mate! :D
